TebLocalPlannerROS:

  odom_topic: odometry/filtered
  map_frame: map

  # Trajectory
  teb_autosize: true
  dt_ref: 0.3
  dt_hysteresis: 0.1
  min_samples: 3
  max_samples: 50
  global_plan_overwrite_orientation: true
  allow_init_with_backwards_motion: false
  max_global_plan_lookahead_dist: 3.0
  feasibility_check_no_poses: 5
  exact_arc_length: false
  publish_feedback: false

  # Robot
  max_vel_x: 2
  max_vel_x_backwards: 0.5
  max_vel_theta: 2
  acc_lim_x: 1
  acc_lim_theta: 1.5
  min_turning_radius: 0.0
  wheelbase: 0.0
  cmd_angle_instead_rotvel: false
  footprint_model:
    type: "polygon"
    vertices: [[-0.21, -0.165], [-0.21, 0.165], [0.21, 0.165], [0.21, -0.165]]

  # GoalTolerance
  xy_goal_tolerance: 0.20
  yaw_goal_tolerance: 0.15
  free_goal_vel: false

  # Obstacles
  min_obstacle_dist: 0.2
  inflation_dist: 0.35
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 15

  # Optimization
  no_inner_iterations: 3
  no_outer_iterations: 2
  optimization_activate: true
  optimization_verbose: false
  penalty_epsilon: 0.1
  weight_max_vel_x: 2.0
  weight_max_vel_theta: 1.0
  weight_acc_lim_x: 1.0
  weight_acc_lim_theta: 1.0
  weight_kinematics_nh: 1000.0
  weight_kinematics_forward_drive: 1.0
  weight_kinematics_turning_radius: 1.0
  weight_optimaltime: 1.0
  weight_obstacle: 50.0

  # Homotopy Class Planner
  enable_homotopy_class_planning: false
  enable_multithreading: false
  simple_exploration: false